# -*- coding: utf-8 -*-
"""EDA_Mini_Project_SV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106u_T0eId1IRvDASxab4YZ9ctjlwud5r
"""

# Importing Data from local
from google.colab import files
files.upload()

# Adding the data to Dataframe
import pandas as pd
df = pd.read_csv("amazon.csv")

# To check the First Look of Data (Raw Data)
df.head()

# To check the size of the Dataset
df.shape

# To check teh column names of the Dataset
df.columns

# Check data types & missing values
df.info()

# To explicitely check the missing values and the total count
df.isnull().sum()

"""We will clean only these columns:

	•	discounted_price
	•	actual_price
	•	discount_percentage
	•	rating
	•	rating_count
"""

# To clean and convert the "Price Columns"
df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

df['actual_price'] = (
    df['actual_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

# To clean "Discount Percentage"
df['discount_percentage'] = (
    df['discount_percentage']
    .str.replace('%', '', regex=False)
    .astype(float)
)

# To clean the "Ratings"
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['rating_count'] = (
    df['rating_count']
    .str.replace(',', '', regex=False)
)
df['rating_count'] = pd.to_numeric(df['rating_count'], errors='coerce')

df.info()

# Statistical Analysis - syntax 'df[col_name].describe()'
df[['discounted_price',
    'actual_price',
    'discount_percentage',
    'rating',
    'rating_count']].describe()

df[['actual_price', 'discounted_price']].describe()

df['rating'].describe()

df['discount_percentage'].describe()

df[['discounted_price', 'actual_price', 'rating_count']].quantile([0.25, 0.5, 0.75, 0.95])

df['category'].value_counts()

df.groupby('category')[['actual_price', 'discounted_price']].mean()

df.groupby('category')['discount_percentage'].mean().sort_values(ascending=False)

df.groupby('category')['rating'].mean().sort_values(ascending=False)

df.groupby('category')['rating_count'].mean().sort_values(ascending=False)